VSCodium (1.100.2, undefined, desktop)
Jupyter Extension Version: 2025.4.1.
Python Extension Version: 2025.4.0.
Pylance Extension not installed.
Platform: linux (x64).
Home = /home/dimgerasimou
Temp Storage folder ~/.config/VSCodium/User/globalStorage/ms-toolsai.jupyter/version-2025.4.1
Workspace folder ~/Numerical_Analysis
23:47:07.575 [info] Telemetry level is off
23:47:07.575 [info] Experiments are disabled, only manually opted experiments are active.
23:47:07.601 [debug] Start refreshing Kernel Picker (1748724427601)
23:47:07.647 [debug] Get Custom Env Variables, Class name = Mm, completed in 46ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
23:47:07.647 [debug] Jupyter Paths /kernels: 
23:47:07.648 [debug] Kernel Spec Root Paths, /usr/share/jupyter/kernels, /usr/local/share/jupyter/kernels, ~/.local/share/jupyter/kernels
23:47:07.901 [debug] KernelProvider switched kernel to id = .jvsc74a57bd016416c10d82bee542b70b4aef187bd840908d77891e02396c26b0abd55e676b6.~/Numerical_Analysis/.venv/python.~/Numerical_Analysis/.venv/python.-m#ipykernel_launcher
23:47:07.902 [debug] start the kernel, options.disableUI=true for ~/Numerical_Analysis/numerical_project.ipynb
23:47:07.904 [debug] Controller selection change completed
23:47:07.923 [debug] Get Custom Env Variables, Class name = Mm, completed in 1ms, has a truthy return value, Arg 1: "~/Numerical_Analysis", Arg 2: "RunPythonCode"
23:47:07.924 [info] Starting Kernel (Python Path: ~/Numerical_Analysis/.venv/bin/python, Venv, 3.13.3) for '~/Numerical_Analysis/numerical_project.ipynb' (disableUI=true)
23:47:08.000 [debug] Get Custom Env Variables, Class name = Mm, completed in 1ms, has a truthy return value, Arg 1: "~/Numerical_Analysis/numerical_project.ipynb", Arg 2: "RunPythonCode"
23:47:08.228 [debug] Start refreshing Interpreter Kernel Picker
23:47:08.487 [debug] Launching kernel .jvsc74a57bd016416c10d82bee542b70b4aef187bd840908d77891e02396c26b0abd55e676b6.~/Numerical_Analysis/.venv/python.~/Numerical_Analysis/.venv/python.-m#ipykernel_launcher for ~/Numerical_Analysis/numerical_project.ipynb in ~/Numerical_Analysis with ports 9001, 9000, 9004, 9002, 9003
23:47:08.527 [debug] Got env vars from Python Ext in 528ms for ~/Numerical_Analysis/.venv/bin/python, with env var count 50.
23:47:08.528 [debug] Getting activated env variables, Class name = xd, completed in 529ms, has a truthy return value, Arg 1: "~/Numerical_Analysis/numerical_project.ipynb", Arg 2: "~/Numerical_Analysis/.venv/bin/python", Arg 3: undefined
23:47:08.533 [info] Process Execution: ~/Numerical_Analysis/.venv/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
23:47:08.537 [info] Process Execution: ~/Numerical_Analysis/.venv/bin/python -m ipykernel_launcher --f=/run/user/1000/jupyter/runtime/kernel-v349b6df449b078cb2eb8d60b3b101521f546ef560.json
    > cwd: ~/Numerical_Analysis
23:47:08.537 [debug] Kernel process 504748.
23:47:08.540 [debug] Got env vars from Python Ext in 618ms for ~/Numerical_Analysis/.venv/bin/python, with env var count 50.
23:47:08.540 [debug] Getting activated env variables, Class name = xd, completed in 618ms, has a truthy return value, Arg 1: "~/Numerical_Analysis", Arg 2: "~/Numerical_Analysis/.venv/bin/python", Arg 3: undefined
23:47:08.546 [info] Process Execution: ~/Numerical_Analysis/.venv/bin/python -m pip list
23:47:08.703 [debug] Refreshed Environments
23:47:08.898 [debug] Kernel output 504748: To connect another client to this kernel, use:
--existing /run/user/1000/jupyter/runtime/kernel-v349b6df449b078cb2eb8d60b3b101521f546ef560.json
23:47:08.980 [debug] Waiting for Raw Session to be ready in postStartRawSession
23:47:08.980 [debug] Waiting for Raw session to be ready, status: connected
23:47:08.981 [debug] Waited for Raw session to be ready & got status: connected
23:47:08.981 [debug] Successfully waited for Raw Session to be ready in postStartRawSession
23:47:08.981 [debug] Kernel status is 'unknown' before requesting kernel info and after ready
23:47:08.981 [debug] Sending request for kernelInfo
23:47:08.985 [debug] Successfully completed postStartRawSession after 1 attempt(s) in 4ms
23:47:09.005 [debug] Requesting Kernel info
23:47:09.009 [info] Kernel successfully started
23:47:09.010 [debug] getDataDirsImpl, Class name = Lr (started execution), Arg 1: "~/Numerical_Analysis/numerical_project.ipynb", Arg 2: "~/Numerical_Analysis/.venv/bin/python"
23:47:09.011 [debug] Get Custom Env Variables, Class name = Mm, completed in 1ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
23:47:09.011 [debug] Jupyter Paths : 
23:47:09.012 [debug] Get Custom Env Variables, Class name = Mm, completed in 0ms, has a truthy return value, Arg 1: "~/Numerical_Analysis/numerical_project.ipynb", Arg 2: "RunPythonCode"
23:47:09.012 [debug] Got env vars from Python Ext in 0ms for ~/Numerical_Analysis/.venv/bin/python, with env var count 50.
23:47:09.012 [debug] Getting activated env variables, Class name = xd, completed in 0ms, has a truthy return value, Arg 1: "~/Numerical_Analysis/numerical_project.ipynb", Arg 2: "~/Numerical_Analysis/.venv/bin/python", Arg 3: undefined
23:47:09.018 [info] Process Execution: ~/Numerical_Analysis/.venv/bin/python ~/.vscode-oss/extensions/ms-toolsai.jupyter-2025.4.1-universal/pythonFiles/printJupyterDataDir.py
23:47:09.031 [debug] Got an empty Jupyter Data Dir from ~/Numerical_Analysis/.venv/bin/python, stderr = undefined
23:47:09.031 [debug] getDataDirsImpl, Class name = Lr, completed in 21ms, has a truthy return value, Arg 1: "~/Numerical_Analysis/numerical_project.ipynb", Arg 2: "~/Numerical_Analysis/.venv/bin/python", Return Value: <Uri:~/.local/share/jupyter>, <Uri:~/Numerical_Analysis/.venv/share/jupyter>, <Uri:/usr/local/share/jupyter>, <Uri:/usr/share/jupyter>
23:47:09.703 [debug] End refreshing Kernel Picker (1748724427601)
23:47:12.306 [debug] Handle Execution of Cells 2,4,7,10,11,14 for ~/Numerical_Analysis/numerical_project.ipynb
23:47:12.316 [debug] Kernel acknowledged execution of cell 2 @ 1748724432315
23:47:13.424 [debug] Kernel acknowledged execution of cell 4 @ 1748724433424
23:47:13.434 [debug] Kernel acknowledged execution of cell 7 @ 1748724433434
23:47:13.546 [debug] Kernel acknowledged execution of cell 10 @ 1748724433546
23:47:13.550 [debug] Kernel acknowledged execution of cell 11 @ 1748724433550
23:47:13.565 [debug] Kernel acknowledged execution of cell 14 @ 1748724433565
23:48:02.811 [info] Dispose Kernel '~/Numerical_Analysis/numerical_project.ipynb' associated with '~/Numerical_Analysis/numerical_project.ipynb'
23:48:02.811 [debug] Cancel pending cells
23:48:02.813 [debug] Shutdown session 5fc16584-34c7-4272-bbb7-8d57835cb050, .jvsc74a57bd016416c10d82bee542b70b4aef187bd840908d77891e02396c26b0abd55e676b6.~/Numerical_Analysis/.venv/python.~/Numerical_Analysis/.venv/python.-m#ipykernel_launcher - start called from Error: 
    at iT.shutdown (~/.vscode-oss/extensions/ms-toolsai.jupyter-2025.4.1-universal/dist/extension.node.js:301:1140)
    at iT.dispose (~/.vscode-oss/extensions/ms-toolsai.jupyter-2025.4.1-universal/dist/extension.node.js:301:623)
    at Is (~/.vscode-oss/extensions/ms-toolsai.jupyter-2025.4.1-universal/dist/extension.node.js:115:867)
    at e (~/.vscode-oss/extensions/ms-toolsai.jupyter-2025.4.1-universal/dist/extension.node.js:282:32549)
    at T_.dispose (~/.vscode-oss/extensions/ms-toolsai.jupyter-2025.4.1-universal/dist/extension.node.js:282:32794)
    at ~/.vscode-oss/extensions/ms-toolsai.jupyter-2025.4.1-universal/dist/extension.node.js:183:1926
    at Array.map (<anonymous>)
    at Rg.dispose (~/.vscode-oss/extensions/ms-toolsai.jupyter-2025.4.1-universal/dist/extension.node.js:183:1917)
    at Object.Ahe (~/.vscode-oss/extensions/ms-toolsai.jupyter-2025.4.1-universal/dist/extension.node.js:447:3706)
    at Object.m (~/.vscode-oss/extensions/ms-toolsai.jupyter-2025.4.1-universal/dist/extension.node.proxy.js:1:901)
    at PQ._deactivate (file:///opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:123:14502)
    at file:///opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:123:12013
    at Array.map (<anonymous>)
    at PQ._deactivateAll (file:///opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:123:12001)
    at PQ.terminate (file:///opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:123:12354)
    at v8.terminate (file:///opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:124:1602)
    at ds (file:///opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:225:5829)
    at MessagePortMain.<anonymous> (file:///opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:225:2284)
    at MessagePortMain.emit (node:events:524:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2949)
23:48:02.813 [debug] Dispose Kernel process 504748.
23:48:02.823 [debug] Kernel got disposed, hence there is no longer a kernel associated with ~/Numerical_Analysis/numerical_project.ipynb
23:48:02.828 [debug] Disposing controller .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher associated with connection .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher 
23:48:02.829 [debug] Disposing controller .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher (Interactive) associated with connection .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher 
23:48:02.829 [debug] Disposing controller .jvsc74a57bd0d2152fd7f0bbc62aa1baff8c990435d1e2c7175d001561303988032604c11a48./sbin/python./sbin/python.-m#ipykernel_launcher associated with connection .jvsc74a57bd0d2152fd7f0bbc62aa1baff8c990435d1e2c7175d001561303988032604c11a48./sbin/python./sbin/python.-m#ipykernel_launcher 
23:48:02.830 [debug] Disposing controller .jvsc74a57bd0d2152fd7f0bbc62aa1baff8c990435d1e2c7175d001561303988032604c11a48./sbin/python./sbin/python.-m#ipykernel_launcher (Interactive) associated with connection .jvsc74a57bd0d2152fd7f0bbc62aa1baff8c990435d1e2c7175d001561303988032604c11a48./sbin/python./sbin/python.-m#ipykernel_launcher 
23:48:02.830 [debug] Disposing controller .jvsc74a57bd0767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90./usr/bin/python./usr/bin/python.-m#ipykernel_launcher associated with connection .jvsc74a57bd0767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90./usr/bin/python./usr/bin/python.-m#ipykernel_launcher 
23:48:02.831 [debug] Disposing controller .jvsc74a57bd0767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90./usr/bin/python./usr/bin/python.-m#ipykernel_launcher (Interactive) associated with connection .jvsc74a57bd0767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90./usr/bin/python./usr/bin/python.-m#ipykernel_launcher 
23:48:02.832 [debug] Disposing controller .jvsc74a57bd04e1d9a8909477db77738c33245c29c7265277ef753467dede8cf3f814cde494e./usr/sbin/python./usr/sbin/python.-m#ipykernel_launcher associated with connection .jvsc74a57bd04e1d9a8909477db77738c33245c29c7265277ef753467dede8cf3f814cde494e./usr/sbin/python./usr/sbin/python.-m#ipykernel_launcher 
23:48:02.832 [debug] Disposing controller .jvsc74a57bd04e1d9a8909477db77738c33245c29c7265277ef753467dede8cf3f814cde494e./usr/sbin/python./usr/sbin/python.-m#ipykernel_launcher (Interactive) associated with connection .jvsc74a57bd04e1d9a8909477db77738c33245c29c7265277ef753467dede8cf3f814cde494e./usr/sbin/python./usr/sbin/python.-m#ipykernel_launcher 
23:48:02.833 [debug] Disposing controller .jvsc74a57bd016416c10d82bee542b70b4aef187bd840908d77891e02396c26b0abd55e676b6.~/Numerical_Analysis/.venv/python.~/Numerical_Analysis/.venv/python.-m#ipykernel_launcher associated with connection .jvsc74a57bd016416c10d82bee542b70b4aef187bd840908d77891e02396c26b0abd55e676b6.~/Numerical_Analysis/.venv/python.~/Numerical_Analysis/.venv/python.-m#ipykernel_launcher and documents file://~/Numerical_Analysis/numerical_project.ipynb
23:48:02.834 [debug] Disposing controller .jvsc74a57bd016416c10d82bee542b70b4aef187bd840908d77891e02396c26b0abd55e676b6.~/Numerical_Analysis/.venv/python.~/Numerical_Analysis/.venv/python.-m#ipykernel_launcher (Interactive) associated with connection .jvsc74a57bd016416c10d82bee542b70b4aef187bd840908d77891e02396c26b0abd55e676b6.~/Numerical_Analysis/.venv/python.~/Numerical_Analysis/.venv/python.-m#ipykernel_launcher 
23:48:02.840 [warn] Failed to delete connection file file:///run/user/1000/jupyter/runtime/kernel-v349b6df449b078cb2eb8d60b3b101521f546ef560.json for pid 504748 Canceled (FileSystemError): Canceled
    at Function._handleError (file:///opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:22541)
    at Object.stat (file:///opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:19418)
    at Gc.delete (~/.vscode-oss/extensions/ms-toolsai.jupyter-2025.4.1-universal/dist/extension.node.js:236:15401)
    at ~/.vscode-oss/extensions/ms-toolsai.jupyter-2025.4.1-universal/dist/extension.node.js:300:469 {
  code: 'Unknown'
}
23:48:02.840 [debug] Disposed Kernel process 504748.
23:48:02.840 [debug] Shutdown session 5fc16584-34c7-4272-bbb7-8d57835cb050, .jvsc74a57bd016416c10d82bee542b70b4aef187bd840908d77891e02396c26b0abd55e676b6.~/Numerical_Analysis/.venv/python.~/Numerical_Analysis/.venv/python.-m#ipykernel_launcher - shutdown complete
