VSCodium (1.100.2, undefined, desktop)
Jupyter Extension Version: 2025.4.1.
Python Extension Version: 2025.4.0.
Pylance Extension not installed.
Platform: linux (x64).
Home = /home/dimgerasimou
Temp Storage folder ~/.config/VSCodium/User/globalStorage/ms-toolsai.jupyter/version-2025.4.1
Workspace folder ~/luben
23:48:26.014 [info] Telemetry level is off
23:48:26.014 [info] Experiments are disabled, only manually opted experiments are active.
23:48:26.038 [debug] Start refreshing Kernel Picker (1748724506038)
23:48:26.082 [debug] Get Custom Env Variables, Class name = Mm, completed in 44ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
23:48:26.082 [debug] Jupyter Paths /kernels: 
23:48:26.083 [debug] Kernel Spec Root Paths, /usr/share/jupyter/kernels, /usr/local/share/jupyter/kernels, ~/.local/share/jupyter/kernels
23:48:26.356 [debug] KernelProvider switched kernel to id = .jvsc74a57bd085a716b4c1b1c5b139d8085c91b41de1a737aaab65f6b4cb15ffa9158f330a1a.~/luben/.venv/python.~/luben/.venv/python.-m#ipykernel_launcher
23:48:26.356 [debug] start the kernel, options.disableUI=true for ~/luben/Untitled-1.ipynb
23:48:26.358 [debug] Controller selection change completed
23:48:26.375 [debug] Get Custom Env Variables, Class name = Mm, completed in 0ms, has a truthy return value, Arg 1: "~/luben", Arg 2: "RunPythonCode"
23:48:26.376 [info] Starting Kernel (Python Path: ~/luben/.venv/bin/python, Venv, 3.13.3) for '~/luben/Untitled-1.ipynb' (disableUI=true)
23:48:26.436 [debug] Get Custom Env Variables, Class name = Mm, completed in 0ms, has a truthy return value, Arg 1: "~/luben/Untitled-1.ipynb", Arg 2: "RunPythonCode"
23:48:26.451 [debug] End refreshing Kernel Picker (1748724506038)
23:48:26.664 [debug] Launching kernel .jvsc74a57bd085a716b4c1b1c5b139d8085c91b41de1a737aaab65f6b4cb15ffa9158f330a1a.~/luben/.venv/python.~/luben/.venv/python.-m#ipykernel_launcher for ~/luben/Untitled-1.ipynb in ~/luben with ports 9001, 9000, 9004, 9002, 9003
23:48:26.750 [debug] Start refreshing Interpreter Kernel Picker
23:48:26.751 [debug] Start refreshing Kernel Picker (1748724506751)
23:48:27.014 [debug] Refreshed Environments
23:48:27.119 [debug] Got env vars from Python Ext in 744ms for ~/luben/.venv/bin/python, with env var count 71.
23:48:27.120 [debug] Getting activated env variables, Class name = xd, completed in 746ms, has a truthy return value, Arg 1: "~/luben", Arg 2: "~/luben/.venv/bin/python", Arg 3: undefined
23:48:27.135 [info] Process Execution: ~/luben/.venv/bin/python -m pip list
23:48:27.138 [debug] Got env vars from Python Ext in 702ms for ~/luben/.venv/bin/python, with env var count 71.
23:48:27.139 [debug] Getting activated env variables, Class name = xd, completed in 703ms, has a truthy return value, Arg 1: "~/luben/Untitled-1.ipynb", Arg 2: "~/luben/.venv/bin/python", Arg 3: undefined
23:48:27.151 [info] Process Execution: ~/luben/.venv/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
23:48:27.162 [info] Process Execution: ~/luben/.venv/bin/python -m ipykernel_launcher --f=/run/user/1000/jupyter/runtime/kernel-v3ea6ecfdba3384ed653924ad883019119f3e6e1df.json
    > cwd: ~/luben
23:48:27.162 [debug] Kernel process 507823.
23:48:27.570 [debug] Kernel output 507823: To connect another client to this kernel, use:
--existing /run/user/1000/jupyter/runtime/kernel-v3ea6ecfdba3384ed653924ad883019119f3e6e1df.json
23:48:27.598 [debug] Waiting for Raw Session to be ready in postStartRawSession
23:48:27.598 [debug] Waiting for Raw session to be ready, status: connected
23:48:27.598 [debug] Waited for Raw session to be ready & got status: connected
23:48:27.598 [debug] Successfully waited for Raw Session to be ready in postStartRawSession
23:48:27.598 [debug] Kernel status is 'unknown' before requesting kernel info and after ready
23:48:27.598 [debug] Sending request for kernelInfo
23:48:27.630 [debug] Successfully completed postStartRawSession after 1 attempt(s) in 32ms
23:48:27.648 [debug] Requesting Kernel info
23:48:27.652 [info] Kernel successfully started
23:48:27.653 [debug] getDataDirsImpl, Class name = Lr (started execution), Arg 1: "~/luben/Untitled-1.ipynb", Arg 2: "~/luben/.venv/bin/python"
23:48:27.655 [debug] Get Custom Env Variables, Class name = Mm, completed in 2ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
23:48:27.655 [debug] Jupyter Paths : 
23:48:27.657 [debug] Get Custom Env Variables, Class name = Mm, completed in 1ms, has a truthy return value, Arg 1: "~/luben/Untitled-1.ipynb", Arg 2: "RunPythonCode"
23:48:27.657 [debug] Got env vars from Python Ext in 1ms for ~/luben/.venv/bin/python, with env var count 71.
23:48:27.657 [debug] Getting activated env variables, Class name = xd, completed in 1ms, has a truthy return value, Arg 1: "~/luben/Untitled-1.ipynb", Arg 2: "~/luben/.venv/bin/python", Arg 3: undefined
23:48:27.664 [info] Process Execution: ~/luben/.venv/bin/python ~/.vscode-oss/extensions/ms-toolsai.jupyter-2025.4.1-universal/pythonFiles/printJupyterDataDir.py
23:48:27.759 [debug] Got an empty Jupyter Data Dir from ~/luben/.venv/bin/python, stderr = undefined
23:48:27.759 [debug] getDataDirsImpl, Class name = Lr, completed in 106ms, has a truthy return value, Arg 1: "~/luben/Untitled-1.ipynb", Arg 2: "~/luben/.venv/bin/python", Return Value: <Uri:~/.local/share/jupyter>, <Uri:~/luben/.venv/share/jupyter>, <Uri:/usr/local/share/jupyter>, <Uri:/usr/share/jupyter>
23:48:28.014 [debug] End refreshing Kernel Picker (1748724506751)
23:48:38.662 [debug] Handle Execution of Cells 1,3,5,7,9 for ~/luben/Untitled-1.ipynb
23:48:38.680 [debug] Kernel acknowledged execution of cell 1 @ 1748724518679
23:48:39.519 [debug] Kernel acknowledged execution of cell 3 @ 1748724519518
23:48:39.527 [debug] Kernel acknowledged execution of cell 5 @ 1748724519527
23:48:39.855 [debug] Kernel acknowledged execution of cell 7 @ 1748724519855
23:48:39.865 [debug] Kernel acknowledged execution of cell 9 @ 1748724519865
23:49:45.220 [debug] Restart kernel command handler for ~/luben/Untitled-1.ipynb
23:49:46.465 [debug] restart the kernel, options.disableUI=false for ~/luben/Untitled-1.ipynb
23:49:46.466 [info] Restart requested ~/luben/Untitled-1.ipynb
23:49:46.467 [debug] Cancel pending cells
23:49:46.469 [debug] Dispose Kernel process 507823.
23:49:46.483 [debug] Get Custom Env Variables, Class name = Mm, completed in 0ms, has a truthy return value, Arg 1: "~/luben/Untitled-1.ipynb", Arg 2: "RunPythonCode"
23:49:46.483 [debug] Got env vars from Python Ext in 1ms for ~/luben/.venv/bin/python, with env var count 71.
23:49:46.483 [debug] Getting activated env variables, Class name = xd, completed in 1ms, has a truthy return value, Arg 1: "~/luben/Untitled-1.ipynb", Arg 2: "~/luben/.venv/bin/python", Arg 3: undefined
23:49:46.491 [info] Process Execution: ~/luben/.venv/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
23:49:46.499 [debug] Launching kernel .jvsc74a57bd085a716b4c1b1c5b139d8085c91b41de1a737aaab65f6b4cb15ffa9158f330a1a.~/luben/.venv/python.~/luben/.venv/python.-m#ipykernel_launcher for ~/luben/Untitled-1.ipynb in ~/luben with ports 9006, 9005, 9009, 9007, 9008
23:49:46.506 [info] Process Execution: ~/luben/.venv/bin/python -m ipykernel_launcher --f=/run/user/1000/jupyter/runtime/kernel-v38d55abd7b9ca77e6377df5044f09dfe8b71650e2.json
    > cwd: ~/luben
23:49:46.506 [debug] Kernel process 508247.
23:49:46.508 [debug] KernelProcess Exited 507823, Exit Code - null 
23:49:46.508 [debug] Disposed Kernel process 507823.
23:49:46.777 [debug] Kernel output 508247: To connect another client to this kernel, use:
--existing /run/user/1000/jupyter/runtime/kernel-v38d55abd7b9ca77e6377df5044f09dfe8b71650e2.json
23:49:46.912 [debug] Waiting for Raw Session to be ready in postStartRawSession
23:49:46.912 [debug] Waiting for Raw session to be ready, status: connected
23:49:46.912 [debug] Waited for Raw session to be ready & got status: connected
23:49:46.912 [debug] Successfully waited for Raw Session to be ready in postStartRawSession
23:49:46.912 [debug] Kernel status is 'unknown' before requesting kernel info and after ready
23:49:46.912 [debug] Sending request for kernelInfo
23:49:46.919 [debug] Successfully completed postStartRawSession after 1 attempt(s) in 7ms
23:49:46.920 [info] Restarted fc4cd600-f707-4236-a419-10ed097d92ac
23:49:46.946 [debug] Requesting Kernel info
23:49:49.382 [debug] Handle Execution of Cells 1,3,5,7,9 for ~/luben/Untitled-1.ipynb
23:49:49.392 [debug] Kernel acknowledged execution of cell 1 @ 1748724589392
23:49:50.325 [debug] Kernel acknowledged execution of cell 3 @ 1748724590325
23:49:50.333 [debug] Kernel acknowledged execution of cell 5 @ 1748724590333
23:49:50.667 [debug] Kernel acknowledged execution of cell 7 @ 1748724590667
23:49:50.675 [debug] Kernel acknowledged execution of cell 9 @ 1748724590675
23:50:17.742 [info] Dispose Kernel '~/luben/Untitled-1.ipynb' associated with '~/luben/Untitled-1.ipynb'
23:50:17.742 [debug] Cancel pending cells
23:50:17.743 [debug] Shutdown session fc4cd600-f707-4236-a419-10ed097d92ac, .jvsc74a57bd085a716b4c1b1c5b139d8085c91b41de1a737aaab65f6b4cb15ffa9158f330a1a.~/luben/.venv/python.~/luben/.venv/python.-m#ipykernel_launcher - start called from Error: 
    at iT.shutdown (~/.vscode-oss/extensions/ms-toolsai.jupyter-2025.4.1-universal/dist/extension.node.js:301:1140)
    at iT.dispose (~/.vscode-oss/extensions/ms-toolsai.jupyter-2025.4.1-universal/dist/extension.node.js:301:623)
    at Is (~/.vscode-oss/extensions/ms-toolsai.jupyter-2025.4.1-universal/dist/extension.node.js:115:867)
    at e (~/.vscode-oss/extensions/ms-toolsai.jupyter-2025.4.1-universal/dist/extension.node.js:282:32549)
    at T_.dispose (~/.vscode-oss/extensions/ms-toolsai.jupyter-2025.4.1-universal/dist/extension.node.js:282:32794)
    at ~/.vscode-oss/extensions/ms-toolsai.jupyter-2025.4.1-universal/dist/extension.node.js:183:1926
    at Array.map (<anonymous>)
    at Rg.dispose (~/.vscode-oss/extensions/ms-toolsai.jupyter-2025.4.1-universal/dist/extension.node.js:183:1917)
    at Object.Ahe (~/.vscode-oss/extensions/ms-toolsai.jupyter-2025.4.1-universal/dist/extension.node.js:447:3706)
    at Object.m (~/.vscode-oss/extensions/ms-toolsai.jupyter-2025.4.1-universal/dist/extension.node.proxy.js:1:901)
    at PQ._deactivate (file:///opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:123:14502)
    at file:///opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:123:12013
    at Array.map (<anonymous>)
    at PQ._deactivateAll (file:///opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:123:12001)
    at PQ.terminate (file:///opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:123:12354)
    at v8.terminate (file:///opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:124:1602)
    at ds (file:///opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:225:5829)
    at MessagePortMain.<anonymous> (file:///opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:225:2284)
    at MessagePortMain.emit (node:events:524:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2949)
23:50:17.743 [debug] Dispose Kernel process 508247.
23:50:17.753 [debug] Kernel got disposed, hence there is no longer a kernel associated with ~/luben/Untitled-1.ipynb
23:50:17.758 [debug] Disposing controller .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher associated with connection .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher 
23:50:17.759 [debug] Disposing controller .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher (Interactive) associated with connection .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher 
23:50:17.759 [debug] Disposing controller .jvsc74a57bd0d2152fd7f0bbc62aa1baff8c990435d1e2c7175d001561303988032604c11a48./sbin/python./sbin/python.-m#ipykernel_launcher associated with connection .jvsc74a57bd0d2152fd7f0bbc62aa1baff8c990435d1e2c7175d001561303988032604c11a48./sbin/python./sbin/python.-m#ipykernel_launcher 
23:50:17.760 [debug] Disposing controller .jvsc74a57bd0d2152fd7f0bbc62aa1baff8c990435d1e2c7175d001561303988032604c11a48./sbin/python./sbin/python.-m#ipykernel_launcher (Interactive) associated with connection .jvsc74a57bd0d2152fd7f0bbc62aa1baff8c990435d1e2c7175d001561303988032604c11a48./sbin/python./sbin/python.-m#ipykernel_launcher 
23:50:17.761 [debug] Disposing controller .jvsc74a57bd0767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90./usr/bin/python./usr/bin/python.-m#ipykernel_launcher associated with connection .jvsc74a57bd0767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90./usr/bin/python./usr/bin/python.-m#ipykernel_launcher 
23:50:17.761 [debug] Disposing controller .jvsc74a57bd0767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90./usr/bin/python./usr/bin/python.-m#ipykernel_launcher (Interactive) associated with connection .jvsc74a57bd0767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90./usr/bin/python./usr/bin/python.-m#ipykernel_launcher 
23:50:17.761 [debug] Disposing controller .jvsc74a57bd04e1d9a8909477db77738c33245c29c7265277ef753467dede8cf3f814cde494e./usr/sbin/python./usr/sbin/python.-m#ipykernel_launcher associated with connection .jvsc74a57bd04e1d9a8909477db77738c33245c29c7265277ef753467dede8cf3f814cde494e./usr/sbin/python./usr/sbin/python.-m#ipykernel_launcher 
23:50:17.762 [debug] Disposing controller .jvsc74a57bd04e1d9a8909477db77738c33245c29c7265277ef753467dede8cf3f814cde494e./usr/sbin/python./usr/sbin/python.-m#ipykernel_launcher (Interactive) associated with connection .jvsc74a57bd04e1d9a8909477db77738c33245c29c7265277ef753467dede8cf3f814cde494e./usr/sbin/python./usr/sbin/python.-m#ipykernel_launcher 
23:50:17.762 [debug] Disposing controller .jvsc74a57bd085a716b4c1b1c5b139d8085c91b41de1a737aaab65f6b4cb15ffa9158f330a1a.~/luben/.venv/python.~/luben/.venv/python.-m#ipykernel_launcher associated with connection .jvsc74a57bd085a716b4c1b1c5b139d8085c91b41de1a737aaab65f6b4cb15ffa9158f330a1a.~/luben/.venv/python.~/luben/.venv/python.-m#ipykernel_launcher and documents file://~/luben/Untitled-1.ipynb
23:50:17.763 [debug] Disposing controller .jvsc74a57bd085a716b4c1b1c5b139d8085c91b41de1a737aaab65f6b4cb15ffa9158f330a1a.~/luben/.venv/python.~/luben/.venv/python.-m#ipykernel_launcher (Interactive) associated with connection .jvsc74a57bd085a716b4c1b1c5b139d8085c91b41de1a737aaab65f6b4cb15ffa9158f330a1a.~/luben/.venv/python.~/luben/.venv/python.-m#ipykernel_launcher 
23:50:17.769 [warn] Failed to delete connection file file:///run/user/1000/jupyter/runtime/kernel-v38d55abd7b9ca77e6377df5044f09dfe8b71650e2.json for pid 508247 Canceled (FileSystemError): Canceled
    at Function._handleError (file:///opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:22541)
    at Object.stat (file:///opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:19418)
    at Gc.delete (~/.vscode-oss/extensions/ms-toolsai.jupyter-2025.4.1-universal/dist/extension.node.js:236:15401)
    at ~/.vscode-oss/extensions/ms-toolsai.jupyter-2025.4.1-universal/dist/extension.node.js:300:469 {
  code: 'Unknown'
}
23:50:17.769 [debug] Disposed Kernel process 508247.
23:50:17.770 [debug] Shutdown session fc4cd600-f707-4236-a419-10ed097d92ac, .jvsc74a57bd085a716b4c1b1c5b139d8085c91b41de1a737aaab65f6b4cb15ffa9158f330a1a.~/luben/.venv/python.~/luben/.venv/python.-m#ipykernel_launcher - shutdown complete
